function setpath

% setpath
%
% Set path to codes needed.
%
% Created: August 18, 2016 by Vasco Curdia
% Copyright 2016 by Vasco Curdia

pathBase = '../../../Matlab/';
pathList = {...
    'vcDSGE',...
    'vcTools',...
    'Misc',...
    'Misc/SimsGensys',...
    'Misc/SimsKF',...
    'Misc/SimsOptimize',...
    'Misc/SimsVARtools',...
    'Misc/JaeWon',...
    };
for j=1:length(MyPath.List)
    pathAdd{j} = [pathBase,pathList{j}];
end
addpath(pathAdd{:})
