#+TITLE: Notes on vcDSGE
#+AUTHOR: Vasco Cúrdia
#+EMAIL: vasco.curdia@sf.frb.org

#+OPTIONS: email:t toc:nil


* TO DO


* 2016-02-01: Misc notes

Estimation actions:
- State: what's the current state of the estimation
- DataAnalysis
- PriorAnalysis
- MaxPost
- MCMC (stage 1, ..., n)
- MCMC Calibration
- MCMC Convergence
- PostAnalysis
- MgLikelihood

Report (for params):
- Prior
- MaxPost
- MCMC
- MCMC Conv
- Mg Likelihood
- Post analysis
All this for params and param ratios

Sim (for variables):
- States
- Forecast
- IRF
- VDecomp
- Hist Decomp
for Var Obs, Var States and Var Add


* 2016-08-18: Aux-Parameters that require numerical solution
If there are aux-parameters that require a numerical solution conditional on
the parameter values then we can proceed as follows.

Create 
m.NumSolveParam with the following fields:
- Names: list of parameter names that link to AuxParam
- Fcn: system of equations to solve. Each equation (function element) is a
  function of elements of AuxParam
- Guess: vector with guess of solution for each NumSolveParam
- Solution: solution of csolve
- rc: return code from csolve

In doing this I need to create AuxParamFcn which will evaluate AuxParam for a
given guess of NumSolveParam.

Once solution is achieved then can map AuxParam to the output of that function.

If length of m.NumSolveParam.Names is zero (empty) then this step is skipped.


* 2016-08-19: Num solution
In case of need to solve some parameters numerically (usually steady state
relations), then let's proceed as follows:
- Set m.NumSolveParam w/ fields:
  - Names
  - Eq
  - Guess
- In PrepModel
  - create sym variables for NumSolveParam.Names
  - AuxParam refers to NumSolveParam.Names and gets properly defined
- In MatsMake
  - Create fcn that evaluates AuxParam given Param and NumSolveParam instances
  - create fcn that assigns Eqs based on Param and AuxParam for a given guess
    of NumSolveParam
  - use csolve to solve this fcn w.r.t. NumSolveParam
  - assign fields to NumSolveParam:
    - Solution
    - rc
    and evaluate NumSolveParam Instances
  - Evaluate AuxParam at NumSolveParam.Solution

Note: we can use nested function so that each evaluation of AuxParam changes
its value in workspace, and the same with NumSolveParam


* 2016-12-21: Multiple objects
Can split DSGE object into several smaller objects that are more self contained

Can do this using a package folder structure so that all objects are associated
with the DSGE (or dsge)
Objects to consider:
- Model
- Data
- Prior
- Posterior
- Options.ParTable
- Options.Sim
- Options.Fig
- Options.IRF
- TimeElapsed
...

The key advantage of having multiple objects is that if in simulations we want
to use different data we don't need to modify the entire DSGE object, just the
data part, can have multiple models, without them being linked to same data,
prior and so on.

Can also consider the case in which model Param refers to the entire set of
Param inputs, while Prior refers only to those that get estimated.

** handle subclasses
If I consider these to all be handle classes then can specify an additional
object that serves as the umbrella of all of this and keep everything
connected:
- Spec

For example, if options for simulations are not initialized and I run IRF, then
it will initialize those options and they stay there available to other sims.

But notice that even in a value class, the master object may contain subobjects
as properties, which can be passed around. The key difference is that each time
they are passed a new copy is created and if they get modified then the
original object is not modified, unless explicitly passed as output.

** Sim object
consider case in which we have one sim class in which the object is a given set
of simulations (sim actions). This way the model mats are created only once for
each sim object, regardless of how many actions are performed.
I think that this is not efficient. Better to create sim options object

* References
#+LATEX_HEADER: \usepackage{color}
#+LATEX_HEADER: \hypersetup{
#+LATEX_HEADER:     colorlinks,
#+LATEX_HEADER:     citecolor=RefColor,
#+LATEX_HEADER:     filecolor=RefColor,
#+LATEX_HEADER:     linkcolor=RefColor,
#+LATEX_HEADER:     urlcolor=RefColor,
#+LATEX_HEADER: }
#+LATEX_HEADER: \usepackage{natbib} 
#+LATEX_HEADER: \usepackage[letterpaper]{geometry}
#+LATEX_HEADER: \geometry{top=1.25in, bottom=1.0in, left=1.0in, right=1.0in}
#+LATEX_HEADER: \setlength{\headheight}{15pt}
#+LATEX_HEADER: \definecolor{RefColor}{rgb}{0.1,0.3,0.5}
#+LATEX_HEADER: \usepackage{setspace}

# If using regular indented paragraphs, including the 1st paragraph
# #+LATEX_HEADER: \usepackage{indentfirst}

# If want to use unindented paragraphs:
#+LATEX_HEADER: \usepackage[parfill]{parskip}

#+LATEX_HEADER: \numberwithin{equation}{section}

bibliographystyle:../../Bibliography/aea
bibliography:../../Bibliography/References.bib
